version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=teacher
      - POSTGRES_PASSWORD=teacher
      - POSTGRES_DB=teacher
    ports:
      - "5433:5432"
    volumes:
      - ./database/docker-data/:/var/lib/postgresql/data
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
volumes:
  db-data: { }
